# Generated by Django 5.0.1 on 2024-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainer_name', models.CharField(max_length=50)),
                ('complainer_address', models.CharField(max_length=128)),
                ('complainer_phone', models.CharField(max_length=10)),
                ('waste_type', models.CharField(max_length=20)),
                ('complaint_desc', models.TextField()),
                ('complain_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
