# Generated by Django 5.0.1 on 2024-03-11 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="News_Blog",
        ),
    ]
