# Generated by Django 5.0.1 on 2024-03-11 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_rename_news_news_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="news_blog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news_blog",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
