# Generated by Django 5.0.1 on 2024-03-12 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0003_news_blog_created_at_news_blog_modified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news_blog",
            name="news_slug",
        ),
    ]
